config/routes.rb
RedditOnRails::Application.routes.draw do

devise_for :users

resources :users

resources :users do
    member do
      get :following, :followers
    end
  end

match 'users/:id' => 'users#show'

resources :pages

resources :links

resources :links do
  member do
    post :vote_up
    post :vote_down
  end
end

resources :relationships, only: [:create, :destroy]

root :to => "pages#index"

end

app/models/link.rb
class Link < ActiveRecord::Base
  make_voteable

  attr_accessible :title, :url

  belongs_to :user

 def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  attr_accessible :followed_id, :follower_id
  



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  has_many :links

  has_many :followed_users, through: :relationships, source: :followed

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
    has_many :followed_users, through: :relationships, source: :followed

has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  make_voter

  def following?(other_user)
    relationships.where(followed_id: other_user.id).first
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.where(followed_id: other_user.id).first.destroy
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

def index

  @link = Link.new

end

def show
end


def new

@link = Link.new

end

def vote_up
  @link = Link.find(params[:id])

  current_user.up_vote(@link)
  redirect_to pages_path , notice: 'Thanks for voting!'
rescue MakeVoteable::Exceptions::AlreadyVotedError
  flash[:error] = 'Already voted!'
  redirect_to pages_path
end

def vote_down
  @link = Link.find(params[:id])
  current_user.down_vote(@link)
  redirect_to pages_path , notice: 'Thanks for voting!'
rescue MakeVoteable::Exceptions::AlreadyVotedError
  flash[:error] = 'Already voted!'
  redirect_to pages_path
end




def create

    @link = Link.new(params[:link])
    @link.user_id = current_user.id

    respond_to do |format|
      if @link.save
        format.html { redirect_to pages_path , notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end

end

def destroy

@link = Link.find(params[:id])
 
@link.destroy
redirect_to root_url

end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


def index

if signed_in?

@links = Link.order("id DESC").all
@link = Link.new
@feedlinks = Link.from_users_followed_by(current_user).order("id DESC").all

end
end


def feedlinks

Link.from_users_followed_by.(current_user)

end



end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  #before_action :signed_in_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find(params[:id])
end


def feed
	Link.from_users_followed_by(self)
end


def index

  @users = User.all
  @user = current_user

end


def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

  <title>Linkshare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Linkshare</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/users">All Users</a></li>
            <li class="dropdown">
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                  <% if current_user.present? %>
            <li><%= link_to 'My Profile', current_user %></li>
            <li><%= link_to 'Account Settings', edit_user_registration_path, :method => :get %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
<li><%= link_to 'Sign In', new_user_session_path %></li>
<li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    
          
          

          


          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= render 'layouts/header' %>
</head>

<body>

<%= render 'layouts/navbar' %>

<p id="alertnotice"><%= notice %></p>
<p ><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/links/_header.html.erb
<head>
  <title>Weblib</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<%# user is logged in, show log out link %>

<ul class="nav nav-pills">	
<% if current_user.present? %>

<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
<%# user is logged out, show login/register link %>
<% else %>
<li><%= link_to 'Sign In', new_user_session_path %></li>
<li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>
</ul>

</head>

app/views/links/new.html.erb
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">

    <%= f.label :title %><br />
    <%= f.text_field :title %><br>

    <%= f.label :url %><br />
    <%= f.text_field :url %><br>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

app/views/links/show.html.erb
something else

app/views/pages/_feed.html.erb
<div style="margin-top: 50px"></div>
<% if @feedlinks.empty? %>
You don't see anything here because you don't follow anyone and you haven't posted any links.  <%= link_to 'Find users to follow', '/users' %> or post a link in the form to your right.
<% else %>

<% @feedlinks.each do |link| %>
<% linkowner = link.user %>

<div class="col-xs-2">
  <div id="voting-links"><br>
  <%= link_to('Vote Up', vote_up_link_path(link), :method => :post )%><br>
  <% link_to('Vote Down', vote_down_link_path(link), :method => :post )%>
  </div>
 <div id="feed-url"> Votes: <%= link.up_votes - link.down_votes %></div>
</div>
<div class="col-xs-10" >
  <b><a href="<%= link.url %>" id="feeditem"><%= link.title %></a></b><br>
  <div id="feed-url">
  <%= link.url %><br>
</div>
<div id="posted-by">
  Posted by: <%= link_to linkowner.username, linkowner %> <%= time_ago_in_words(link.created_at) %> ago.
</div>
  
  <div id="feed-delete">
<% if signed_in? %>
  <% if current_user.id == linkowner.id %>
    <%= link_to "delete", link, method: :delete,
                                     data: { confirm: "Are you sure you want to delete this link?" },
                                     title: link.title %>

  <% end %>
  <% end %>

</div>
<br>
</div>


<% end %>
<% end %>

app/views/pages/_linkform.html.erb
<br>
<h4>Add a Link:</h4>

<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>

      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

  <% end %>

<div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

</div>
<div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url %><br>
    <p class="help-block">Use "http://www.link.com" format</p>
</div>

  
    <%= f.submit "Add Link", class: "btn btn-default" %>

  

  <% end %>

<br>

app/views/pages/index.html.erb
<% require 'make_voteable' %>

<div class="container">

<% if signed_in? %>

<div class="container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          
         <%= render 'feed' %>
          
          <div class="row">
           
          
          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
         <%= render 'linkform' %>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->


</div>

<% else %>
<script type="text/javascript">
    window.location.href="/users/sign_in"  // put your correct path in a string here
  </script>


<% end %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
  <div id="follow_form">


<% else %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>

  </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.where(followed_id: @user.id).first,
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/index.html.erb
<div class="container" style="margin-top: 50px;">
	

<% if signed_in? %>
<% @users.each do |user| %>
<%= link_to user.username, user  %><br>
User Since: <%= user.created_at %><br>
Links Posted: <%= user.links.count %><br>
<br><br>
<% end %>

<% else %>

You need to sign in to see users

<% end %>


</div>

app/views/users/show.html.erb
<div class="container" style="margin-top: 50px;">
<div class="row">

	<div class="col-8">
Email: <%= @user.email %><br>
Member Since: <%= @user.created_at %><br>
Last Logged In: <%= @user.last_sign_in_at %><br>
<%= render 'shared/stats' %>

<% if current_user == @user %>

<% else %>
<%= render 'follow_form' if signed_in? %>
<% end %>
</div>



</div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
<div class="row">
  <div class="col-4">
      <h1><%= @user.username %></h1>
      <span><%= link_to "View profile", @user %></span>
      <span><b>Links:</b> <%= @user.links.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
</div>
<div class="col-4">
      <% if @users.any? %>
       
          <% @users.each do |user| %>
           <%= link_to user.username, user %><br>
          <% end %>
   
      <% end %>
  
  </div> 
</div>
</div>